name: tillash_app
description: A Flutter project for Tillash App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^17.0.1

  # Maps
  google_maps_flutter: ^2.14.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.0.0

  # Useful extras
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  google_fonts: ^4.0.5
